---
- hosts: all
  become: yes
  tasks:
   
   - name: i want to install the nginx server
     apt:
      name: nginx
      state: present
   - name:
     template:
      src: /mytemplates/index.j2
      dest: /var/www/html/index.html
  

   - name: start nginx service
     service:
      name: nginx
      state: started
      