---
- hosts: all
  become: yes
  tasks:
   - name: i want to update the ubuntu server
     apt:
      update_cache: yes
  
   - name: i want to install the nginx server
     apt:
      name: nginx
      state: latest

   - name: start nginx service
     service:
      name: nginx
      state: started
      enabled: yes